# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b91a8f573f39195be20288538714349a18180361e905cb853928d10615b0f0a55e9f1a299ad651500f14ecd6eccbf0f422158956d35b446cc2050ac4770d3567

test:
  secret_key_base: 511f3212977e151b976a859732806c37baaf1e9ef0e4b97f4c1c7dc939e1ce3e05863bdc77246b29d2648cf3384bf3fc6cf0a2a2688d15c3a1057f51ea6d0c3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
